### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by zeruniverse** [PABCSoft/FastNeuralColor#1]
For your English version, this image (pure white) crashes your software:  
[a.zip](https://github.com/PABCSoft/FastNeuralColor/files/2183252/a.zip)

By the way,

+ it's toooooo slow. Takes more than 3 minutes in my laptop. Consider using some deep learning libraries with parallel computing features (or even better, CUDA)

+ Consider not to use non-English letters in your [English branch](https://github.com/PABCSoft/FastNeuralColor/blob/master/FastNeuralColor.pas), those letters don't display under my Linux terminal since I don't have your locale.

**Comment by PABCSoft** [comment]
> it's toooooo slow. Takes more than 3 minutes in my laptop. Consider using some deep learning libraries with parallel computing features (or even better, CUDA).

Unfortunately, this is so. The input image is reduced to 720x560 pixels, which takes a long time to process. Parallel computing is used everywhere, but it's important to understand that after GPU and pure machine code, using CPU with managed(.NET) code will seem really long. In the new version, I significantly reduced the image size, which reduced processing time to 30 seconds. By the way, how Did you manage to run a program on Linux with Windows Forms?

> Consider not to use non-English letters in your English branch, those letters don't display under my Linux terminal since I don't have your locale.

Could have missed something, I'll check.

**Comment by PABCSoft** [comment]
> For your English version, this image (pure white) crashes your software:

Now looked - do not understand anything. Incomprehensibly...

**Comment by zeruniverse** [comment]
Can you reproduce this bug? I ran your software in Windows10 with the pure
white image I attached in this issue

**Comment by PABCSoft** [comment]
Now I looked-Yes, it is a bug, but here's how to fix it - not clear. This happens when the input normalization (in the case of faded photos). Division by 0 followed by operations on infinity.
```
newB := System.Convert.ToInt16(System.Math.Round((In_Address^ - newMinB) * 255 / (newMaxB - newMinB)));
```
If the input is just a white image, the maximum and minimum value is 255. Difference is 0. Well, the division by 0.

**Comment by PABCSoft** [comment]
The solution is to add to the difference of 1. In the new version I will correct. Result with Your image:

![default](https://user-images.githubusercontent.com/36363358/42616723-e97df2b0-85b7-11e8-9364-153893d12700.jpg)

Perhaps the new version will fit under the version GAN.

**Comment by PABCSoft** [comment]
Updated version:
1. Reduced the size of the processed image. On my laptop 7 years ago, processing takes 61 seconds.
2. Fixed bug with white image.
