### ISSUE TITLE
Model weights are possibly not used correctly

### ISSUE THREAD

**Issue by zeruniverse** [PABCSoft/FastNeuralColor#2]
In your implementation, I didn't see any centerization and normalization of input (y).

In my torch implementation, I have:

1. normalize y (gray scale) to a float number of `[0,1]` (if y is 0-255, divide by 255)
2. assign `y'=y-0.5` so `y'` has range [-0.5,0.5]
3. pass `y'` into the model.
4. The output is `u'v'`
5. You need UV to convert back to RGB. `U=0.43601035 * u'`, `V=0.61497538*v'`
6. Now you have standard yUV (in float point format). You can use standard yuv2rgb (Wikipedia has following, but it's not exactly accurate):
![capture](https://user-images.githubusercontent.com/4648756/42556366-383231dc-84a0-11e8-9c51-52c69b94d752.PNG)

7. The RGB from step 6 is all in range `[0,1]`. If not, you should force x>1 to 1 and x<0 to 0.
8. `int(round(rgb*255))` if necessary

I didn't see step 2 is done in your source code and it seems you are doing minus on V `OriginV - 128` which is not necessary (actually I think you did it wrong but I'm just not certain.)

**Comment by PABCSoft** [comment]
> assign y'=y-0.5 so y' has range [-0.5,0.5]
Alignment set:
```
(RGB[((W * y) + x) * 3] * 0.299 + RGB[((W * y) + x) * 3 + 1] * 0.587 + RGB[((W * y) + x) * 3 + 2] * 0.114) / 255 - 0.5;
```
First divide by 255 and then subtract 0.5.

> The RGB from step 6 is all in range [0,1]. If not, you should force x>1 to 1 and x<0 to 0.

I have otherwise, I used the conversion from Wikipedia, it gave a value within 0..255.
